### ISSUE TITLE
Please add buildroot instructions

### ISSUE THREAD

**Issue by wyaeld** [jprjr/docker-tinynode#4]
Hi @jprjr this is really interesting

Can you please add a section to the readme to explain the steps to produce the rootfs

From what I can tell, some of the scripts there are helpers to do that, but appear to be making assumptions about a directory layout on the host system

I'd love to know enough to be able to maintain the images, or produce similar, it seems like an excellent pattern.

**Comment by jprjr** [comment]
No problem! I'll get something written up shortly.

As much fun as I had making this image, though, you might want to take a look at https://github.com/gliderlabs/docker-alpine as a better alternative to buildroot-based images. You get the best of both worlds that way - small images, but with a package manager and precompiled packages. I think their NodeJS image winds up being the same size as this one.

Getting a buildroot image built takes a long time, and you lose some of that composability factor that Docker brings in. IE, with the buildroot images you can't just make a Dockerfile like `FROM something; RUN install stuff`, you wind up rebuilding the whole image just to add a package, due to the lack of a package manager.

It's definitely worth knowing *how* to do it, though. I learned a lot about the inner workings of Linux, compiling software, etc by getting really down and dirty and making this thing.

**Comment by jprjr** [comment]
@wyaeld , I added some docs into the README: https://github.com/jprjr/docker-tinynode/blob/master/README.md

Try that out and let me know how it goes!

**Comment by wyaeld** [comment]
Thanks.  I also ended up having a really good look at alpine, and liking it
a lot.  I have running Rails applications in under 70mb.  Its a nice
package management approach, and I agree its really the best of both worlds.

Seems a bit hard to get responses out of the package maintainer though.

**Comment by wyaeld** [comment]
instructions look great.  Figured out how to get the alpine environment working and submitted patches for new aports too.
